/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SubjectId = IDL.Nat;
export const ChapterId = IDL.Nat;
export const ExamPaperId = IDL.Nat;
export const NoteId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExamPaper = IDL.Record({
  'id' : ExamPaperId,
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'subjectId' : SubjectId,
});
export const Subject = IDL.Record({
  'id' : SubjectId,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'description' : IDL.Text,
});
export const Chapter = IDL.Record({
  'id' : ChapterId,
  'title' : IDL.Text,
  'order' : IDL.Nat,
  'description' : IDL.Text,
  'subjectId' : SubjectId,
});
export const Time = IDL.Int;
export const Note = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdDate' : Time,
  'chapterId' : ChapterId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChapter' : IDL.Func(
      [IDL.Text, SubjectId, IDL.Nat, IDL.Text],
      [ChapterId],
      [],
    ),
  'addExamPaper' : IDL.Func(
      [IDL.Text, SubjectId, IDL.Nat, IDL.Text],
      [ExamPaperId],
      [],
    ),
  'addNote' : IDL.Func([IDL.Text, IDL.Text, ChapterId], [NoteId], []),
  'addSubject' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [SubjectId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllExamPapers' : IDL.Func([], [IDL.Vec(ExamPaper)], ['query']),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChaptersBySubject' : IDL.Func([SubjectId], [IDL.Vec(Chapter)], ['query']),
  'getLatestNotes' : IDL.Func([IDL.Nat], [IDL.Vec(Note)], ['query']),
  'getNotesByChapter' : IDL.Func([ChapterId], [IDL.Vec(Note)], ['query']),
  'getSubjectStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalExamPapers' : IDL.Nat,
          'totalSubjects' : IDL.Nat,
          'totalNotes' : IDL.Nat,
          'totalChapters' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'preloadSubjects' : IDL.Func([], [], []),
  'searchAll' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'subjects' : IDL.Vec(Subject),
          'examPapers' : IDL.Vec(ExamPaper),
          'chapters' : IDL.Vec(Chapter),
          'notes' : IDL.Vec(Note),
        }),
      ],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SubjectId = IDL.Nat;
  const ChapterId = IDL.Nat;
  const ExamPaperId = IDL.Nat;
  const NoteId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExamPaper = IDL.Record({
    'id' : ExamPaperId,
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'subjectId' : SubjectId,
  });
  const Subject = IDL.Record({
    'id' : SubjectId,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'description' : IDL.Text,
  });
  const Chapter = IDL.Record({
    'id' : ChapterId,
    'title' : IDL.Text,
    'order' : IDL.Nat,
    'description' : IDL.Text,
    'subjectId' : SubjectId,
  });
  const Time = IDL.Int;
  const Note = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdDate' : Time,
    'chapterId' : ChapterId,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChapter' : IDL.Func(
        [IDL.Text, SubjectId, IDL.Nat, IDL.Text],
        [ChapterId],
        [],
      ),
    'addExamPaper' : IDL.Func(
        [IDL.Text, SubjectId, IDL.Nat, IDL.Text],
        [ExamPaperId],
        [],
      ),
    'addNote' : IDL.Func([IDL.Text, IDL.Text, ChapterId], [NoteId], []),
    'addSubject' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [SubjectId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllExamPapers' : IDL.Func([], [IDL.Vec(ExamPaper)], ['query']),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChaptersBySubject' : IDL.Func(
        [SubjectId],
        [IDL.Vec(Chapter)],
        ['query'],
      ),
    'getLatestNotes' : IDL.Func([IDL.Nat], [IDL.Vec(Note)], ['query']),
    'getNotesByChapter' : IDL.Func([ChapterId], [IDL.Vec(Note)], ['query']),
    'getSubjectStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalExamPapers' : IDL.Nat,
            'totalSubjects' : IDL.Nat,
            'totalNotes' : IDL.Nat,
            'totalChapters' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'preloadSubjects' : IDL.Func([], [], []),
    'searchAll' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'subjects' : IDL.Vec(Subject),
            'examPapers' : IDL.Vec(ExamPaper),
            'chapters' : IDL.Vec(Chapter),
            'notes' : IDL.Vec(Note),
          }),
        ],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };