/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : ChapterId,
  'title' : string,
  'order' : bigint,
  'description' : string,
  'subjectId' : SubjectId,
}
export type ChapterId = bigint;
export interface ExamPaper {
  'id' : ExamPaperId,
  'title' : string,
  'year' : bigint,
  'description' : string,
  'subjectId' : SubjectId,
}
export type ExamPaperId = bigint;
export interface Note {
  'id' : NoteId,
  'title' : string,
  'content' : string,
  'createdDate' : Time,
  'chapterId' : ChapterId,
}
export type NoteId = bigint;
export interface Subject {
  'id' : SubjectId,
  'icon' : string,
  'name' : string,
  'color' : string,
  'description' : string,
}
export type SubjectId = bigint;
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChapter' : ActorMethod<[string, SubjectId, bigint, string], ChapterId>,
  'addExamPaper' : ActorMethod<
    [string, SubjectId, bigint, string],
    ExamPaperId
  >,
  'addNote' : ActorMethod<[string, string, ChapterId], NoteId>,
  'addSubject' : ActorMethod<[string, string, string, string], SubjectId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllExamPapers' : ActorMethod<[], Array<ExamPaper>>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChaptersBySubject' : ActorMethod<[SubjectId], Array<Chapter>>,
  'getLatestNotes' : ActorMethod<[bigint], Array<Note>>,
  'getNotesByChapter' : ActorMethod<[ChapterId], Array<Note>>,
  'getSubjectStats' : ActorMethod<
    [],
    {
      'totalExamPapers' : bigint,
      'totalSubjects' : bigint,
      'totalNotes' : bigint,
      'totalChapters' : bigint,
    }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'preloadSubjects' : ActorMethod<[], undefined>,
  'searchAll' : ActorMethod<
    [string],
    {
      'subjects' : Array<Subject>,
      'examPapers' : Array<ExamPaper>,
      'chapters' : Array<Chapter>,
      'notes' : Array<Note>,
    }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];